version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf:/etc/nginx/conf.d
    ports:
      - "80:80"
      
  php:
    image: php:7.4-fpm
    volumes:
      - ./html:/usr/share/nginx/html