name: Test webserv

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: make

    - name: Start web server
      run: ./webserv &
      continue-on-error: true

    - name: Execute tester
      run: |
        # Define a function to press enter when prompted
        press_enter() {
          while true; do
            sleep 1
            printf '\n'
          done
        }
        
        # Run the press_enter function in the background
        press_enter &

        # Store the PID of the background process
        PRESS_ENTER_PID=$!

        # Run the tester script
        ./tester http://localhost:80

        # Kill the press_enter function
        kill $PRESS_ENTER_PID
