name: Test webserv

on:
  push: # Trigger this action on every push

jobs:
  build-and-test:
    runs-on: macos-latest # Change to macOS runner

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Build the project
      run: make

    - name: Start the webserv
      run: ./webserv &

    - name: Wait for the webserv to start
      run: sleep 5 # Give the webserv a few seconds to start

    - name: Test the webserv
      run: ./tester http://localhost:80
