name: Test webserv

on:
  push:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Build the project
      run: make

    - name: Start the webserv
      run: ./webserv &

    - name: Wait for the webserv to start
      run: sleep 5

    - name: Test the webserv with continuous Enter key presses
      run: |
        expect -c "
        spawn ./tester http://localhost:80
        while {1} {
          send \"\r\"
          sleep 1
        }
        "
