name: Test webserv

on:
  push:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Build the project
      run: make

    - name: Start the webserv
      run: ./webserv &

    - name: Wait for the webserv to start
      run: sleep 5

    - name: Run tester
      run: |
        ./tester http://localhost:80 &
        TESTER_PID=$!
        sleep 1
        for i in {1..60}; do
          osascript -e 'tell application "System Events" to key code 36'
          sleep 1
        done
        wait $TESTER_PID
